version: "3.7"

networks:
  app:
    driver: bridge

services:

    database:
        build:
            context: ./db
            dockerfile: ./Dockerfile
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            -   3307:3306 
        expose:
            -   3307
        networks:
            -   app
        environment:
            MYSQL_HOST: localhost
            MYSQL_ROOT_PASSWORD: dashboard
            MYSQL_PASSWORD: dashboard
            MYSQL_USER: dashboard
            MYSQL_DATABASE: dashboard
            MYSQL_ALLOW_EMPTY_PASSWORD: ok

    server:
        build:
            context: ./server
        ports:
            -   8080:8080
        networks:
            -   app
        links:
            -   database:database
        depends_on:
            -   database

    react-app:
        build:
            context: ./client
        stdin_open: true
        networks:
            -   app
        ports:
            -   8092:8092
        depends_on:
            -   server