-- MySQL Script generated by MySQL Workbench
-- Wed Dec 23 01:34:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dashboard
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dashboard` ;

-- -----------------------------------------------------
-- Schema dashboard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dashboard` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `dashboard` ;

-- -----------------------------------------------------
-- Table `dashboard`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashboard`.`user` ;

CREATE TABLE IF NOT EXISTS `dashboard`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashboard`.`widget`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashboard`.`widget` ;

CREATE TABLE IF NOT EXISTS `dashboard`.`widget` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(100) NULL,
  `widgetId` BIGINT NULL,
  `name` VARCHAR(45) NULL,
  `state` INT NOT NULL,
  `data` VARCHAR(1000) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

/*
-- -----------------------------------------------------
-- Table `dashboard`.`user_has_user_widget`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashboard`.`user_has_user_widget` ;

CREATE TABLE IF NOT EXISTS `dashboard`.`user_has_user_widget` (
  `user_id` INT NOT NULL,
  `user_widget_id` INT NOT NULL,
  `position` INT NULL,
  `position` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`, `user_widget_id`),
  INDEX `fk_user_has_user_widget_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_user_widget_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `dashboard`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashboard`.`user_has_widget`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashboard`.`user_has_widget` ;

CREATE TABLE IF NOT EXISTS `dashboard`.`user_has_widget` (
  `user_id` INT NOT NULL,
  `widget_id` INT NOT NULL,
  `position` INT NULL,
  PRIMARY KEY (`user_id`, `widget_id`),
  INDEX `fk_user_has_widjet_widjet1_idx` (`widget_id` ASC) VISIBLE,
  INDEX `fk_user_has_widjet_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_widjet_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `dashboard`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_widjet_widjet1`
    FOREIGN KEY (`widget_id`)
    REFERENCES `dashboard`.`widget` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
*/